[package]
name = "los_logger"
version = "2.0.0"
edition = "2021"

[dependencies]
chrono = "0.4"
dotenv = "0.15.0"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
