services:
  api:
    build:
      context: .
    restart: always
    environment:
      LOSL_DB_USER: ${LOSL_DB_USER}
      LOSL_DB_PASS: ${LOSL_DB_PASS}
      ATLAS_HOST: ${ATLAS_HOST}
      ATLAS_PORT: ${ATLAS_PORT}
      LOSL_DB_NAME: ${LOSL_DB_NAME}
      LOSL_DB_SCHEMA: ${LOSL_DB_SCHEMA}
      LOSL_DB_SSLMODE: ${LOSL_DB_SSLMODE}
      LOSL_DB_CONNTIMEOUT: ${LOSL_DB_CONNTIMEOUT}
      LOSL_API_PORT: ${LOSL_API_PORT}
      LOSL_LOGFILE: ${LOSL_LOGFILE}
      LOSL_WBEACON: ${LOSL_WBEACON}
      TZ: Asia/Manila
    ports:
      - ${LOSL_API_PORT}:${LOSL_API_PORT}
    volumes:
      - .:/app
    networks:
      - atlasnet
      
networks:
  atlasnet:
    external: true
