services:
  api:
    build:
      context: .
    restart: always
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_DIR: ${LOG_DIR}
      LOG_FILE_NAME: ${LOG_FILE_NAME}
      LOG_FILE_LOC: ${LOG_FILE_LOC}
      BEACON_TARGET: ${BEACON_TARGET}
      TZ: Asia/Manila
    volumes:
      - ${LOG_DIR}:/${LOG_DIR}
    networks:
      - atlasnet
      
networks:
  atlasnet:
    external: true
